import type { Metadata } from "next";
import LegalPageShell from "@/components/LegalPageShell";

export const metadata: Metadata = {
  title: "AI Transparency & Disclaimer",
  description: "How and where Global Ready AIEval uses artificial intelligence, and its limitations.",
};

export default function AiTransparencyPage() {
  return (
    <LegalPageShell title="AI Transparency & AI Disclaimer" effectiveDate="01.09.2026">
      <p>Global Ready AIEval uses artificial intelligence to provide certain training, practice and career-preparation features.</p>
      <p>This notice explains:</p>
      <ul>
        <li>Where artificial intelligence is used</li>
        <li>What AI-generated scores and feedback mean</li>
        <li>The limitations of AI</li>
        <li>How users should interpret AI-generated results</li>
        <li>What Global Ready AIEval does not use AI to do</li>
      </ul>
      <p>
        Global Ready AIEval is operated by:
        <br />
        John Chiatu Bimi
        <br />
        Mastweg 83
        <br />
        42349 Wuppertal
        <br />
        Germany
        <br />
        Email: <a href="mailto:contact@globalready.tech">contact@globalready.tech</a>
      </p>

      <h2>1. Our Use of Artificial Intelligence</h2>
      <p>Global Ready AIEval uses artificial intelligence as part of its educational and career-preparation services. AI may be used to support features including:</p>
      <ul>
        <li>AI interview simulations</li>
        <li>Interview questions</li>
        <li>Follow-up interview questions</li>
        <li>Interview feedback</li>
        <li>Interview performance scores</li>
        <li>Practice assessments</li>
        <li>Evaluation exercises</li>
        <li>Explanations</li>
        <li>Suggested areas for improvement</li>
        <li>CV and resume feedback</li>
        <li>Training recommendations</li>
        <li>Learning guidance</li>
        <li>Other educational functionality</li>
      </ul>
      <p>Our AI-powered features may use third-party artificial intelligence technology, including Google Gemini.</p>

      <h2>2. You Will Be Told When You Are Interacting With AI</h2>
      <p>Where a user directly interacts with an AI-powered feature, Global Ready AIEval will clearly indicate that artificial intelligence is being used.</p>
      <p>For example, before beginning an AI interview simulation, users will be informed that: the interviewer is AI-powered and the questions, scores and feedback may be generated using artificial intelligence.</p>
      <p>Users should not assume that an AI interviewer, evaluator or feedback system is a human recruiter, career adviser or representative of any third-party company.</p>

      <h2>3. AI Interview Simulator</h2>
      <p>The Global Ready AIEval AI Interview Simulator is a training and self-assessment tool. It is designed to help users:</p>
      <ul>
        <li>Practise answering interview questions</li>
        <li>Improve communication</li>
        <li>Develop stronger explanations</li>
        <li>Identify areas for improvement</li>
        <li>Become familiar with AI evaluation interview formats</li>
        <li>Build confidence before applying or interviewing independently</li>
      </ul>
      <p>The simulator does not conduct an official employment interview on behalf of Mercor, Outlier, Alignerr, Micro1 or any other third-party company.</p>
      <p>Unless expressly stated otherwise, questions generated by the simulator are independently created training questions and are not official questions supplied by those companies.</p>

      <h2>4. AI-Generated Scores</h2>
      <p>Some training activities may generate scores or performance ratings. These scores are intended solely to help users understand their current performance within the Global Ready AIEval training environment.</p>
      <p>An AI-generated score:</p>
      <ul>
        <li>Is not an official employment assessment</li>
        <li>Is not an accreditation</li>
        <li>Is not a professional qualification</li>
        <li>Is not a hiring recommendation</li>
        <li>Does not determine whether a person is employable</li>
        <li>Does not guarantee assessment success</li>
        <li>Does not guarantee acceptance onto a third-party platform</li>
      </ul>
      <p>A high score does not mean that a third-party company will accept or hire the user.</p>
      <p>A low score does not mean that the user is unsuitable for AI evaluation work or other employment.</p>

      <h2>5. No Automated Hiring or Recruitment Decisions</h2>
      <p>Global Ready AIEval does not use its AI interview simulator or training scores to make employment decisions about users. Our AI systems are not intended to decide whether a user should:</p>
      <ul>
        <li>Be employed</li>
        <li>Be rejected for employment</li>
        <li>Receive a freelance contract</li>
        <li>Be accepted onto a third-party work platform</li>
        <li>Receive a project</li>
        <li>Receive a particular rate of pay</li>
        <li>Receive access to employment</li>
      </ul>
      <p>Global Ready AIEval does not provide employers with automated hiring decisions based on users&apos; training scores.</p>
      <p>The AI functionality is designed for: education, practice, training, feedback and self-assessment.</p>
      <p>
        If Global Ready AIEval materially changes the purpose of an AI system in the future, including by
        introducing functionality that affects recruitment, employment, admission or other significant decisions,
        we will reassess the applicable legal and regulatory requirements before introducing that functionality.
      </p>

      <h2>6. AI Output Can Be Wrong</h2>
      <p>Artificial intelligence does not always produce correct results. AI-generated information may:</p>
      <ul>
        <li>Contain factual errors</li>
        <li>Misinterpret a response</li>
        <li>Miss relevant context</li>
        <li>Produce inconsistent scores</li>
        <li>Generate incomplete explanations</li>
        <li>Provide an inappropriate recommendation</li>
        <li>Produce outdated information</li>
        <li>Overlook errors</li>
        <li>Incorrectly identify errors</li>
        <li>Generate information that appears confident but is inaccurate</li>
      </ul>
      <p>This is sometimes referred to as AI hallucination.</p>
      <p>Users should therefore treat AI-generated output as training guidance rather than absolute fact.</p>

      <h2>7. AI Scores May Vary</h2>
      <p>AI-generated assessments are probabilistic. This means that similar responses may sometimes receive different:</p>
      <ul>
        <li>Questions</li>
        <li>Feedback</li>
        <li>Scores</li>
        <li>Explanations</li>
        <li>Recommendations</li>
      </ul>
      <p>A score should therefore be understood as an educational indicator produced within the Global Ready AIEval training environment rather than as an objective or guaranteed measurement of professional ability.</p>

      <h2>8. Bias and Fairness</h2>
      <p>Artificial intelligence systems can reflect limitations or biases contained in:</p>
      <ul>
        <li>Training data</li>
        <li>Model design</li>
        <li>Evaluation criteria</li>
        <li>User prompts</li>
        <li>Language patterns</li>
        <li>Context available to the system</li>
      </ul>
      <p>Global Ready AIEval aims to use AI responsibly and to design training features that focus on relevant professional skills.</p>
      <p>Our AI systems should not intentionally evaluate users based on irrelevant personal characteristics such as:</p>
      <ul>
        <li>Race</li>
        <li>Ethnic origin</li>
        <li>Religion</li>
        <li>Political beliefs</li>
        <li>Sexual orientation</li>
        <li>Health status</li>
        <li>Disability</li>
        <li>Other protected or sensitive personal characteristics</li>
      </ul>
      <p>
        Where users believe AI feedback contains inappropriate, discriminatory or materially biased output, they
        are encouraged to report it to <a href="mailto:contact@globalready.tech">contact@globalready.tech</a>
      </p>

      <h2>9. No Emotion Recognition or Biometric Categorisation</h2>
      <p>Global Ready AIEval does not use its AI interview simulator to perform emotion recognition or biometric categorisation for hiring or employment purposes.</p>
      <p>The Service does not intend to determine characteristics such as a user&apos;s personality, trustworthiness, employability or professional suitability based on facial expressions, biometric characteristics or inferred emotions.</p>
      <p>If functionality involving biometric or emotion-related processing were ever considered in the future, it would be subject to separate legal, data-protection and AI-governance assessment before implementation.</p>

      <h2>10. CV and Career Recommendations</h2>
      <p>AI may be used to assist users with CV, resume or career-preparation activities. AI-generated CV suggestions may include:</p>
      <ul>
        <li>Wording improvements</li>
        <li>Skills identification</li>
        <li>Experience presentation</li>
        <li>Suggested keywords</li>
        <li>Career-development recommendations</li>
        <li>Interview-preparation guidance</li>
      </ul>
      <p>These recommendations are educational suggestions. Global Ready AIEval does not guarantee that following an AI-generated CV recommendation will result in:</p>
      <ul>
        <li>An interview</li>
        <li>Employment</li>
        <li>Platform acceptance</li>
        <li>Higher earnings</li>
        <li>A particular recruitment outcome</li>
      </ul>
      <p>Users remain responsible for ensuring that information contained in their CV is truthful and accurate.</p>
      <p>Users should never add qualifications, experience or achievements that they do not genuinely possess.</p>

      <h2>11. Users Remain Responsible for Their Decisions</h2>
      <p>AI-generated content should assist users rather than replace their judgment. Users remain responsible for:</p>
      <ul>
        <li>Their applications</li>
        <li>Their CV</li>
        <li>Their interview answers</li>
        <li>Their assessments</li>
        <li>Their career decisions</li>
        <li>Their third-party platform accounts</li>
        <li>Their work submissions</li>
        <li>Verifying important information before relying on it</li>
      </ul>
      <p>Users should review AI-generated content before using it outside Global Ready AIEval.</p>

      <h2>12. AI Must Not Be Used to Facilitate Cheating</h2>
      <p>Global Ready AIEval&apos;s AI tools are intended for training and preparation. They must not be used to:</p>
      <ul>
        <li>Obtain prohibited real-time answers during a live assessment</li>
        <li>Complete a third-party assessment on behalf of another person</li>
        <li>Circumvent third-party assessment controls</li>
        <li>Impersonate another applicant</li>
        <li>Generate work that a third-party platform requires the user to complete independently</li>
        <li>Facilitate fraud or misrepresentation</li>
        <li>Process leaked or confidential assessment material</li>
      </ul>
      <p>Users remain responsible for complying with the rules of any third-party platform on which they apply or work.</p>

      <h2>13. Global Ready AIEval Does Not Represent Third-Party Platforms</h2>
      <p>AI-generated content referring to companies such as:</p>
      <ul>
        <li>Mercor</li>
        <li>Outlier</li>
        <li>Alignerr</li>
        <li>Micro1</li>
        <li>DataAnnotation</li>
        <li>Scale AI</li>
        <li>TELUS Digital</li>
        <li>Appen</li>
        <li>DataForce</li>
        <li>Other AI training or evaluation platforms</li>
      </ul>
      <p>does not mean that the relevant company has supplied, approved or endorsed the content.</p>
      <p>Global Ready AIEval is an independent training provider.</p>
      <p>Third-party company names may be used to provide relevant career context, but our simulations and AI-generated guidance should not be interpreted as official instructions from those companies.</p>

      <h2>14. Third-Party AI Providers</h2>
      <p>Global Ready AIEval may integrate third-party AI models and infrastructure, including Google Gemini, to provide AI-powered functionality.</p>
      <p>Third-party providers may process information necessary to generate the requested AI output.</p>
      <p>The processing of personal data through AI-powered features is explained in our Privacy Policy.</p>
      <p>Global Ready AIEval evaluates the use of third-party AI systems and seeks to use them in a manner consistent with applicable data-protection and AI-governance requirements.</p>

      <h2>15. Human Support and Reporting Problems</h2>
      <p>Although Global Ready AIEval uses automated AI functionality, users may contact us if they believe:</p>
      <ul>
        <li>An AI-generated score is clearly inappropriate</li>
        <li>Feedback contains a serious factual error</li>
        <li>AI output appears discriminatory or inappropriate</li>
        <li>The system generated harmful or offensive content</li>
        <li>A technical problem affected an assessment</li>
        <li>There is another significant concern regarding an AI-powered feature</li>
      </ul>
      <p>
        Contact: <a href="mailto:contact@globalready.tech">contact@globalready.tech</a>
      </p>
      <p>Reporting a concern does not necessarily mean that every AI score will be manually reassessed, but legitimate issues may be reviewed and used to improve the Service where appropriate.</p>

      <h2>16. AI-Generated Content Is Not Professional Advice</h2>
      <p>AI-generated feedback and recommendations available through Global Ready AIEval are intended for educational and career-preparation purposes. They should not be treated as:</p>
      <ul>
        <li>Legal advice</li>
        <li>Financial advice</li>
        <li>Medical advice</li>
        <li>Psychological advice</li>
        <li>Tax advice</li>
        <li>Professional recruitment advice</li>
        <li>A guarantee concerning employment or income</li>
      </ul>
      <p>Where professional advice is required, users should consult an appropriately qualified professional.</p>

      <h2>17. Updates to AI Systems</h2>
      <p>Artificial intelligence technology changes rapidly. Global Ready AIEval may:</p>
      <ul>
        <li>Update AI models</li>
        <li>Change AI providers</li>
        <li>Improve prompts</li>
        <li>Modify evaluation criteria</li>
        <li>Introduce safeguards</li>
        <li>Change scoring methodologies</li>
        <li>Add or remove AI functionality</li>
      </ul>
      <p>Changes may be made to improve: reliability, accuracy, safety, security, user experience, legal compliance, training quality.</p>
      <p>Where a material change affects how personal data is processed, our Privacy Policy will be updated as required.</p>
      <p>Where a material change affects the legal classification or intended purpose of an AI feature, Global Ready AIEval will reassess the applicable AI-governance requirements.</p>

      <h2>18. Responsible Use of AI</h2>
      <p>Global Ready AIEval supports responsible use of artificial intelligence. Our approach is based on principles including:</p>
      <ul>
        <li>Transparency</li>
        <li>Human responsibility</li>
        <li>Privacy</li>
        <li>Security</li>
        <li>Fairness</li>
        <li>Appropriate human oversight</li>
        <li>Clear limitations</li>
        <li>Responsible training use</li>
      </ul>
      <p>AI is used to support learning. It should not replace the user&apos;s responsibility to develop and demonstrate their own skills.</p>

      <h2>19. Contact</h2>
      <p>Questions or concerns regarding the use of artificial intelligence through Global Ready AIEval may be sent to:</p>
      <p>
        Global Ready AIEval
        <br />
        Operated by John Chiatu Bimi
        <br />
        Mastweg 83
        <br />
        42349 Wuppertal
        <br />
        Germany
        <br />
        Email: <a href="mailto:contact@globalready.tech">contact@globalready.tech</a>
      </p>
    </LegalPageShell>
  );
}
